package pojo;
// Generated Jan 19, 2019 2:11:30 AM by Hibernate Tools 4.3.1



/**
 * Assemblyline generated by hbm2java
 */
public class Assemblyline  implements java.io.Serializable {


     private Integer idAssemblyline;
     private Components components;
     private Products products;
     private int validation;

    public Assemblyline() {
    }

    public Assemblyline(Components components, Products products, int validation) {
       this.components = components;
       this.products = products;
       this.validation = validation;
    }
   
    public Integer getIdAssemblyline() {
        return this.idAssemblyline;
    }
    
    public void setIdAssemblyline(Integer idAssemblyline) {
        this.idAssemblyline = idAssemblyline;
    }
    public Components getComponents() {
        return this.components;
    }
    
    public void setComponents(Components components) {
        this.components = components;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public int getValidation() {
        return this.validation;
    }
    
    public void setValidation(int validation) {
        this.validation = validation;
    }




}


