package pojo;
// Generated Jan 19, 2019 2:11:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Components generated by hbm2java
 */
public class Components  implements java.io.Serializable {


     private Integer idComponents;
     private String name;
     private String model;
     private String manufacturer;
     private int costs;
     private String parameters;
     private Set<Assemblyline> assemblylines = new HashSet<Assemblyline>(0);

    public Components() {
    }

	
    public Components(String name, String model, String manufacturer, int costs, String parameters) {
        this.name = name;
        this.model = model;
        this.manufacturer = manufacturer;
        this.costs = costs;
        this.parameters = parameters;
    }
    public Components(String name, String model, String manufacturer, int costs, String parameters, Set<Assemblyline> assemblylines) {
       this.name = name;
       this.model = model;
       this.manufacturer = manufacturer;
       this.costs = costs;
       this.parameters = parameters;
       this.assemblylines = assemblylines;
    }
   
    public Integer getIdComponents() {
        return this.idComponents;
    }
    
    public void setIdComponents(Integer idComponents) {
        this.idComponents = idComponents;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }
    public int getCosts() {
        return this.costs;
    }
    
    public void setCosts(int costs) {
        this.costs = costs;
    }
    public String getParameters() {
        return this.parameters;
    }
    
    public void setParameters(String parameters) {
        this.parameters = parameters;
    }
    public Set<Assemblyline> getAssemblylines() {
        return this.assemblylines;
    }
    
    public void setAssemblylines(Set<Assemblyline> assemblylines) {
        this.assemblylines = assemblylines;
    }




}


