package pojo;
// Generated Jan 19, 2019 2:11:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer idProducts;
     private String name;
     private String code;
     private Date date;
     private int price;
     private Set<Assemblyline> assemblylines = new HashSet<Assemblyline>(0);

    public Products() {
    }

	
    public Products(String name, String code, int price) {
        this.name = name;
        this.code = code;
        this.price = price;
    }
    public Products(String name, String code, Date date, int price, Set<Assemblyline> assemblylines) {
       this.name = name;
       this.code = code;
       this.date = date;
       this.price = price;
       this.assemblylines = assemblylines;
    }
   
    public Integer getIdProducts() {
        return this.idProducts;
    }
    
    public void setIdProducts(Integer idProducts) {
        this.idProducts = idProducts;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public Set<Assemblyline> getAssemblylines() {
        return this.assemblylines;
    }
    
    public void setAssemblylines(Set<Assemblyline> assemblylines) {
        this.assemblylines = assemblylines;
    }




}


